### PR TITLE
Fixes an exception when parsing intercalated errors and success msgs into generic_response

### LINKED ISSUE #287: generic_response's adapter throws an exception when receiving an error in an intermediate command
The following throws when it shouldn't:

```cpp
   config cfg;

   request req;
   req.push("PING", "hello");
   req.push("set", "mykey");
   req.push("get", "mykey");

   boost::redis::generic_response resp;

   asio::io_context ioc;
   connection conn{ioc};

   conn.async_run(cfg, asio::detached);

   conn.async_exec(req, resp, [&](auto, auto) {
      std::cout << "on async_exec" << std::endl;
      conn.cancel();
   });

   ioc.run();
```

The server will respond with, at least, with nodes like the following: [success, error, success].

This causes the adapter to behave incorrectly in [these lines](https://github.com/boostorg/redis/blob/20ab2c7e70ad9c9bd696acc69644a85c645c77bc/include/boost/redis/adapter/detail/adapters.hpp#L142-L171). The error node will emplace an error response in the result, and the next success node will invoke `result::value()`, throwing an exception.

I don't think this is super urgent but should be kept track of. If I have the time to refactor adapters at some point, I'll fix it.

### PR DESCRIPTION
**Pull request by anarthal**
close #287

### CODE REVIEW

File: test/test_conn_exec_error.cpp [hunk 1]
```diff
@@ -292,4 +292,38 @@ BOOST_AUTO_TEST_CASE(subscriber_wrong_syntax)
...
+   conn.async_run(cfg, [&](error_code ec) {
+      BOOST_TEST(ec == net::error::operation_aborted);
+      run_finished = true;
+   });
+
+   conn.async_exec(req, resp, [&](error_code ec, std::size_t) {
+      BOOST_TEST(ec == error_code());
+      exec_finished = true;
+      conn.cancel();
+   });
```
Comment (mzimbres) [inline test/test_conn_exec_error.cpp:319]: Early feedback: when `async_exec` fails to execute the commands of a request it should complete with an error. I think all adapters work like this.

Comment (anarthal) [reply test/test_conn_exec_error.cpp:319]: How the hell do tests pass then? lol

Comment (anarthal) [reply test/test_conn_exec_error.cpp:319]: Hm, none of general_aggregate nor general_simple seem to be setting the output error code on failure.

**Comment by anarthal** [comment]
What should we do with this @mzimbres? It looks like adapters don't set the output error code when they receive an individual error. So `async_exec` succeeds, but the obtained response is an error. This kind of makes sense, since there was no networking problem, but the server answered with an error.
