### PR TITLE
Makes async_receive2 not cancel on reconnection

### LINKED ISSUE #331: Rework async_receive to consume all elements in the channel
As I work on the `generic_flat_response` implementation I noticed that `async_receive` and its sync counterpart `receive` are too cumbersome and inefficient to work with.  At the moment the general for of the receive loop looks like this

```cpp
for (error_code ec;;) {
   conn->receive(ec);
   if (ec == error::sync_receive_push_failed) {
      ec = {};
      co_await conn->async_receive(asio::redirect_error(asio::use_awaitable, ec));
   }

   if (ec)
      break;  // Connection lost, break so we can reconnect to channels.

   ...

   consume_one(resp);
}
```

The `async_receive` function does not actually receive a response, it just removes its size from the channel. However it does not make sense to consume only one message at time since the response passed to `conn.set_receive_response()` might contain multiple pushes (i.e. the channel size). If we can make `async_receive` consume/accumulate all elements in the channel, the loop gets simpler and there is no need for the `consume_one` function that is inefficient since it rotates the response (any performance gain made by `generic_flat_response` will be eclipsed by these rotations). The general form of the loop consuming pushes would become

```cpp
for (error_code ec;;) {
   // Accumulates all sizes in the channel.
   co_await conn->async_receive2(asio::redirect_error(asio::use_awaitable, ec));
   if (ec)
      break;  // Connection lost, break so we can reconnect to channels.

   for (auto const& elem: resp)
      // Process the node.

   resp.clear();
}
```

Things to do

  - Add an `async_receive2` function that consumes all messages in the channel.
  - Deprecate `async_receive`, `receive` and `consume_one`.

### PR DESCRIPTION
**Pull request by anarthal**
async_receive2 is now only cancelled after calling connection::cancel() or using per-operation cancellation
Adds a restriction to only have one outstanding async_receive2 operation per connection
Adds error::already_running
Adds support for asio::cancel_after for async_receive2
Deprecates cancel(operation::receive)
Adds more documentation to async_receive2

close #331

### CODE REVIEW

**Comment by anarthal** [comment]
Still lacking unit tests for the FSM.

File: include/boost/redis/connection.hpp [hunk 1]
```diff
@@ -785,27 +807,68 @@ class basic_connection {
...
+    * eventually timeout. To avoid that apps that expect server pushes
+    * should call this function continuously in a loop.
+    *
+    * This function should be used instead of the deprecated @ref async_receive.
+    * It differs from `async_receive` in the following:
+    *
+    * @li `async_receive` is designed to consume a single push message at a time.
+    *     This can be inefficient when receiving lots of server pushes.
+    *     `async_receive2` is batch-oriented, and will only suspend once if
+    *     several pushes are received in a single network packet.
```
Comment (mzimbres) [inline include/boost/redis/connection.hpp]:
```suggestion
    *     256 push messages accumulate internally.
```

Comment (anarthal) [reply include/boost/redis/connection.hpp]: Hmmm, no. The reader suspends if 256 push messages accumulate. `async_receive2` is the consumer side. I'll try to rephrase this though.
